version: "3.4"

services:

  db:
    build:
      context: "./db"
    restart: always
    environment:
     - DB_PASS=qqq
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    #    ports:
    # - "6380:6379"
    restart: always

  php:
    build:
      context: "./php"
    hostname: "cm_php"
    volumes:
     - "app_code:/app"
    depends_on:
     - "db"
    environment:
     - MATRIX_URL

  nginx:
    build:
      context: "./nginx"
    hostname: "cm_nginx"
    ports:
     - "${HTTP_PORT:-80}:80"
    volumes:
     - "app_code:/app"
    depends_on:
     - "php"
    environment:
      PS1: "\\u@\\h:\\w\\$$ "

volumes:
  app_code:
  db_data:
